[build.environment]
NODE_VERSION = "20"

[build]
base = "/docs"
publish = ".vitepress/dist"
command = "pnpm run docs:build"

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = '''
    max-age=31536000,
    immutable'''

[[headers]]
for = "/_translations/*"
[headers.values]
x-robots-tag = "noindex"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
